### ISSUE TITLE
Simple use of async::task leaks process memory

### ISSUE THREAD

**Issue by dok-net** [microsoft/cpp-async#1]
Take this MCVE:
```
#include "async/task.h"
#include "async/awaitable_get.h"

inline async::task<int> run_async(int id)
{
	co_await std::suspend_never();
	co_return id;
}

bool main_coro(int id)
{
	auto r = async::awaitable_get(run_async(id));
	return r == id;
}

int main(int argc, char* argv[]) {
	int i = 0;
	for (;;++i) {
		if (!main_coro(i))
			break;
	}
	return i;
}
```
Within seconds, process memory increases from 1MB to 1GB and onward.

Built and run with Microsoft Visual Studio 2022 17.6.2 and cpp-async release 1.0.0 as C++20 command line app.

**Comment by jbaldwin** [comment]
The `task` class appears to be missing a destructor that explicitly calls the `coroutine`'s `.destroy()` function.  I would imagine every time you make a new coroutine it is leaking upon completion.

See https://github.com/jbaldwin/libcoro/blob/main/inc/coro/task.hpp destructor for reference.

**Comment by davidmatson** [comment]
I took a look at this case today. It's worth noting that the example above uses only a single thread (main), and if a thread hop were added, rather than continuing to execute the subsequent code as the continuation of each task, the coroutines could complete and reclaim the memory.

Stated another way, his behavior occurs because task is designed to reclaim coroutine frame memory as soon as the coroutine completes rather than as soon as the task is destructed. I experimented with capturing the coroutine frame and destroying it when task_state is destroyed (i.e., when the task is destroyed), but I believe that change would break existing documented behavior for fire-and-forget. From the README:

```c++
inline async::task<void> fire_and_forget()
{
    /* do some work */

    co_await /* some awaitable object */;

    if (/* something bad happens*/)
    {
        throw std::runtime_error{ "fire_and_forget failed" };
    }

    co_return;
}

inline async::task<void> fire_and_forget_except_crash_on_failure()
{
    try
    {
        co_await fire_and_forget();
    }
    catch (...)
    {
        std::terminate();
    }
}

int main()
{
    {
        // uncomment one of the next lines (to ignore or crash on exception):
        //fire_and_forget();
        fire_and_forget_except_crash_on_failure();
    }

    std::this_thread::sleep_for(std::chrono::seconds{ 1 });
}
```

Also from the README:
```
When working with the task<T> directly (rather than only passing it directly to co_await), a caller may cancel execution
of any code that would resume after the task completes by destructing the task. (Destructing the task does not stop the
task's coroutine from running, just any continuation that would run after the task's coroutine completes.) As a result,
an exception thrown from a task will be ignored if no caller consumes the task's result. (A caller can avoid this
behavior by consuming the task's result and handling the exception differently; for example by co_awaiting the task from
another coroutine and calling std::terminate when it throws.)

Internally, task<T> destroys the coroutine frame as soon as the coroutine completes; it does not wait until the task has
destructed (which would only be after executing any code that will run next). Both options here involve tradeoffs; the
alternative would avoid the need for an internal heap allocation when creating the task at the expense of keeping
(potentially large) coroutine frame memory in use longer.
```

Given the design choice to support fire-and-forget (which avoids crashes when the task destructor runs after the task has co_awaited something else) and to reclaim memory on completion of the continuation, I think the behavior in the repro above is likely to be unavoidably by design. Let me know if you think there's another option I'm missing though that wouldn't require breaking the existing, documented behavior.

**Comment by dok-net** [comment]
No offense, but after re-checking the main branch, from my limited knowledge I disagree with the statement
> Internally, task<T> destroys the coroutine frame as soon as the coroutine completes;

as the only instance of the `destroy()` function getting called is in `awaitable_get.h`.

Being forced to do thread synchronization outside the co-routine framework seems to be running against the grain of the whole concept. Could you adapt the MCVE to show how to stop it from leaking heap memory? Thank you.

**Comment by davidmatson** [comment]
I believe it should be destroyed by the compiler. The [C++ Standard](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/n4868.pdf) (at least, the final draft I can read) has:

<blockquote>
The coroutine state is destroyed when control flows off the end of the coroutine or the destroy member function (17.12.4.5) of a coroutine handle (17.12.4) that refers to the coroutine is invoked.
</blockquote>

**Comment by dok-net** [comment]
> I'm looking a bit more to see what's happening.

Thanks. Something IS leaking on each compiler that I have tried :-)

**Comment by davidmatson** [comment]
OK, I'm optimistic there's an answer here, but I think I'm fighting against a compiler bug in MSVC - changing code that shouldn't matter causes it to crash.

Here's a simplified repro, not using async::task<t>:
```c++
#include <coroutine>
#include <exception>
#include <memory>
#include <tuple>

namespace
{
    struct custom_suspend final
    {
        custom_suspend(void* handle) noexcept : m_handle{ std::coroutine_handle<>::from_address(handle) } {}

        [[nodiscard]] constexpr bool await_ready() const noexcept { return false; }

        std::coroutine_handle<> await_suspend(std::coroutine_handle<> handle) noexcept
        {
            //if (handle.address() != m_handle.address())
            //{
            //    std::terminate();
            //}
            handle.destroy();
            return std::noop_coroutine();
        }

        void await_resume() const noexcept { std::terminate(); }

    private:
        std::coroutine_handle<> m_handle;
    };

    struct simple_task final
    {
        struct promise_type;

        simple_task(std::coroutine_handle<promise_type> handle, std::shared_ptr<int> value) noexcept :
            m_handle{ handle }, m_value{ value }
        {}

        constexpr bool await_ready() const noexcept { return true; }

        void await_suspend(std::coroutine_handle<>) const noexcept { std::terminate(); }

        int await_resume() const noexcept { return *m_value; }

        simple_task& operator=(const simple_task&) = delete;
        simple_task& operator=(simple_task&&) noexcept = delete;

        struct promise_type final
        {
            promise_type() noexcept : m_handle{ std::coroutine_handle<promise_type>::from_promise(*this) } {}

            simple_task get_return_object() noexcept
            {
                std::shared_ptr<int> value{ std::make_shared<int>() };
                m_value = std::weak_ptr<int>{ value };
                return { m_handle, std::move(value) };
            }

            constexpr std::suspend_never initial_suspend() const noexcept { return {}; }

            void unhandled_exception() const { std::rethrow_exception(std::current_exception()); }

            void return_value(int value) const noexcept
            {
                std::shared_ptr<int> task{ m_value.lock() };

                if (task)
                {
                    *task = value;
                }
            }
            custom_suspend final_suspend() const noexcept { return { m_handle.address() }; }

        private:
            std::coroutine_handle<promise_type> m_handle;
            std::weak_ptr<int> m_value;
        };

    private:
        std::coroutine_handle<promise_type> m_handle;
        std::shared_ptr<int> m_value;
    };
}

inline simple_task run_async(int id) { co_return id; }

bool main_coro(int id)
{
    auto r = run_async(id).await_resume();
    return r == id;
}

int main(int argc, char* argv[])
{
    std::ignore = argc;
    std::ignore = argv;
    int i = 0;
    for (;; ++i)
    {
        if (!main_coro(i))
            break;
    }
    return i;
}
```

If I don't call handle.destroy(), it leaks, because the coroutine never "flows off the end". But if I do call handle.destroy() and uncomment the test above (which shouldn't do much of anything - the two values are the same), it crashes due to heap corruption.

I'm trying to see if I can get in contact with the MSVC team to report the crash above, and I'm seeing if I can find a way to thread the needle in async::task<T> to allow it to destroy the handle without triggering whatever compiler bug causes a crash if things aren't exactly just so to make the compiler happy.

**Comment by davidmatson** [comment]
@dok-net - can you confirm the PR fixes this bug for you?

I had to disable symmetric transfer for now - there doesn't appear to be a way to get MSVC at least to clean up the coroutine handle, support fire-and-forget tasks, and use symmetric transfer all at the same time. I'm going to try to follow up with the MSVC team to see if there's a bug (or something I'm misunderstanding about what's possible).

**Comment by dok-net** [comment]
You could have waited on my go-ahead :-) I have been able to run some tests today with MSVC and GCC, and found the issue as I had reported it solved. I'm proposing the changes I had to make for GCC the other day in a new PR now.

**Comment by davidmatson** [comment]
I had forgotten it would auto-close this issue once I merged the PR. Glad to hear it's fixed! I'll continue the discussion on the GCC changes on the other PR.
